version: 2.1

parameters:
  run_integration_tests:
    type: boolean
    default: false
  deploy:
    type: boolean
    default: false

jobs:
  mytestjob:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - when:
          condition: << pipeline.parameters.deploy >>
          steps:
            - run: echo "Preparing to deploy version"
            - run: echo "Preparing to deploy version << pipeline.parameters.tag-to-deploy >>"

workflows:
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - mytestjob
